server:
  port: 8085

app:
  batch:
      jobs:
        "jobMovie"
spring:
  datasource:
    #Postgres database config
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/movies
    username: user
    password: password
    hikari:
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      test-on-borrow: true
      connection-timeout: 60002
      idle-timeout: 50001
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        jdbc:
          time_zone: UTC
    open-in-view: false
  batch:
    jdbc:
      schema: classpath:org/springframework/batch/core/schema-postgres.sql
      initialize-schema: always
    job:
      enabled: false


